#ifndef __APPARENCE_H
#define __APPARENCE_H

#include "Global.h"

const unsigned int __OBJGROUP_SHORT_SWORD	      			= 1;
const unsigned int __OBJGROUP_LONG_SWORD     				= 2;
const unsigned int __OBJGROUP_FLAIL				      		= 3;
const unsigned int __OBJGROUP_MORNING_STAR      			= 4;
const unsigned int __OBJGROUP_WARHAMMER		      		= 5;
const unsigned int __OBJGROUP_SPEAR    						= 6; 
const unsigned int __OBJGROUP_AXE		      				= 7;
const unsigned int __OBJGROUP_LEATHER_ARMOR	      		= 8;
const unsigned int __OBJGROUP_WELL_TALK                  = 9;
const unsigned int __OBJGROUP_CHEST_TALK                 = 10;
const unsigned int __OBJGROUP_LEATHER_HELM      			= 11;
const unsigned int __OBJGROUP_MAGE_SPELLBOOK		      	= 12;
const unsigned int __OBJGROUP_PRIEST_ANKH    			   = 13;
const unsigned int __OBJGROUP_SCROLL                     = 14;
const unsigned int __OBJGROUP_WOODEN_DOOR_CLOSED         = 15;
const unsigned int __OBJGROUP_WOODEN_DOOR_OPENED         = 16;
const unsigned int __OBJGROUP_WOODEN_CHAIR               = 17;
const unsigned int __OBJGROUP_CHEST_I  		      		= 18;
const unsigned int __OBJGROUP_CHEST_OPEN_I		         = 19;
const unsigned int __OBJGROUP_CHEST2_I                   = 20;
const unsigned int __OBJGROUP_LONGUE_VUE                 = 27;
const unsigned int __OBJGROUP_TORCH				      	   = 28;
const unsigned int __OBJGROUP_IRON_KEY    					= 29;
const unsigned int __OBJGROUP_BLUE_KEY		      			= 30;
const unsigned int __OBJGROUP_WEIRD_KEY			      	= 31;
const unsigned int __OBJGROUP_GOLD_KEY 	   				= 32;
const unsigned int __OBJGROUP_KEY_HOLD	   	   			= 33;
const unsigned int __OBJGROUP_EMPTY_MUG      				= 34;
const unsigned int __OBJGROUP_BEER_MUG	      				= 35;
const unsigned int __OBJGROUP_BEER_MUG_TOO_FULL    		= 36;
const unsigned int __OBJGROUP_EMPTY_GLASS    				= 37;
const unsigned int __OBJGROUP_BEVERAGE			      		= 38;
const unsigned int __OBJGROUP_CUP_FULL					      = 39;
const unsigned int __OBJGROUP_WOODEN_CUP     				= 40;
const unsigned int __OBJGROUP_CHEST				      		= 41;
const unsigned int __OBJGROUP_CHEST_OPEN				      = 42;
const unsigned int __OBJGROUP_BASKET_CLOSE      			= 43;
const unsigned int __OBJGROUP_BASKET_OPEN			      	= 44;
const unsigned int __OBJGROUP_RED_BOOK    					= 45;
const unsigned int __OBJGROUP_GREY_BOOK	      			= 46;
const unsigned int __OBJGROUP_BROWN_BOOK			      	= 47;
const unsigned int __OBJGROUP_BACKPACK    					= 48;
const unsigned int __OBJGROUP_BANDAGES_PACK	      		= 49;
const unsigned int __OBJGROUP_BANDAGE_1      				= 50;
const unsigned int __OBJGROUP_BANDAGE_2		      		= 51;
const unsigned int __OBJGROUP_WOODEN_BOWL				      = 52;
const unsigned int __OBJGROUP_WOODEN_VASE    				= 53;
const unsigned int __OBJGROUP_GOLD_BAR			      		= 54;
const unsigned int __OBJGROUP_GOLD_BAR_PACK			      = 55;
const unsigned int __OBJGROUP_BRONZE_BAR     				= 56;
const unsigned int __OBJGROUP_BRONZE_BAR_PACK      		= 57;
const unsigned int __OBJGROUP_IRON_BAR		      			= 58;
const unsigned int __OBJGROUP_IRON_BAR_PACK	      		= 59;
const unsigned int __OBJGROUP_BROOM_ON_WALL	      		= 60;
const unsigned int __OBJGROUP_PIOCHE			      		= 61;
const unsigned int __OBJGROUP_BROOM_ON_FLOOR	      		= 62;
const unsigned int __OBJGROUP_HAMMER			      		= 63;
const unsigned int __OBJGROUP_PINCES			      		= 64;
const unsigned int __OBJGROUP_BALANCE			      		= 65;
const unsigned int __OBJGROUP_HOURGLASS		      		= 66;
const unsigned int __OBJGROUP_EPROUVETTE_6_PACKS      	= 67;
const unsigned int __OBJGROUP_EPROUVETTE_3_PACKS	      = 68;
const unsigned int __OBJGROUP_EPROUVETTE_ALONE     		= 69;
const unsigned int __OBJGROUP_BUCHE_DE_BOIS	      		= 70;
const unsigned int __OBJGROUP_WOOD_PACK_CLASSED		      = 71;
const unsigned int __OBJGROUP_WOOD_PACK_MIXED      		= 72;
const unsigned int __OBJGROUP_JAMBON	      				= 73;
const unsigned int __OBJGROUP_LONG_SAUSAGE	      		= 74;
const unsigned int __OBJGROUP_SAUSAGE_PACK	      		= 75;
const unsigned int __OBJGROUP_FAT_JAMBON		      		= 76;
const unsigned int __OBJGROUP_CHIKEN			      		= 77;
const unsigned int __OBJGROUP_BREAD				      		= 78;
const unsigned int __OBJGROUP_PACK_OF_PASTRIES	      	= 79;
const unsigned int __OBJGROUP_WATERBASKET		      		= 80;
const unsigned int __OBJGROUP_FISHING_POLE	      		= 81;
const unsigned int __OBJGROUP_DEAD_FISHES			      	= 82;
const unsigned int __OBJGROUP_EMPTY_BASKET	      		= 83;
const unsigned int __OBJGROUP_ARROW				      		= 84;
const unsigned int __OBJGROUP_ARROW_PACK		      		= 85;
const unsigned int __OBJGROUP_BOW				      		= 86;
const unsigned int __OBJGROUP_CROSSBOW			      		= 87;
const unsigned int __OBJGROUP_BANJO				      		= 88;
const unsigned int __OBJGROUP_TAMBOUR				      	= 89;
const unsigned int __OBJGROUP_MAP		      				= 90;
const unsigned int __OBJGROUP_SCIE				      		= 91;
const unsigned int __OBJGROUP_LONG_WHOOL_BALL      		= 92;
const unsigned int __OBJGROUP_WHOOL_BALL	      			= 93;
const unsigned int __OBJGROUP_GREEN_WHOOL_BALL	      	= 94;
const unsigned int __OBJGROUP_BLUE_WHOOL_BALL	      	= 95;
const unsigned int __OBJGROUP_SHOVEL		      			= 96;
const unsigned int __OBJGROUP_BLUE_POTION	      			= 97;
const unsigned int __OBJGROUP_YELLOW_POTION     			= 98;
const unsigned int __OBJGROUP_BLACK_POTION      			= 99;
const unsigned int __OBJGROUP_EMPTY_POTION      			= 100;
const unsigned int __OBJGROUP_PURPLE_POTION		      	= 101;
const unsigned int __OBJGROUP_BASKET_FULL_WATER    		= 102;
const unsigned int __OBJGROUP_BASKET_FULL_FRUIT    		= 103;
const unsigned int __OBJGROUP_WOODEN_ROUND_CHAIR      	= 104;
const unsigned int __OBJGROUP_WOODEN_CHAIR_2		      	= 105;
const unsigned int __OBJGROUP_WOODEN_ROUND_CHAIR_2       = 106;
const unsigned int __OBJGROUP_CRATES		      			= 107;
const unsigned int __OBJGROUP_RECTANGLE_CRATES	      	= 108;
const unsigned int __OBJGROUP_CUBIQ_CRATES      			= 109;
const unsigned int __OBJGROUP_KITCHEN_BOWL      			= 110;
const unsigned int __OBJGROUP_KITCHEN_SPOON		      	= 111;
const unsigned int __OBJGROUP_KITCHEN_FORK	      		= 112;
const unsigned int __OBJGROUP_KITCHEN_KNIFE	      		= 113;
const unsigned int __OBJGROUP_ROULEAU_A_PATRE	      	= 114;
const unsigned int __OBJGROUP_CHANDELLE		      	   = 115;
const unsigned int __OBJGROUP_CHANDELLE_SUR_PIED      	= 116;
const unsigned int __OBJGROUP_MIRROR	      				= 117;
const unsigned int __OBJGROUP_STAFF1			      		= 118;
const unsigned int __OBJGROUP_MACE                  		= 119;
const unsigned int __OBJGROUP_SPIKE_MACE		      		= 120;
const unsigned int __OBJGROUP_MAUL				      		= 121;
const unsigned int __OBJGROUP_DOUBLE_AXE		      		= 122;
const unsigned int __OBJGROUP_SINGLE_AXE		      		= 123;
const unsigned int __OBJGROUP_BASTARD_SWORD	      		= 124;
const unsigned int __OBJGROUP_SPEAR_AXE	      			= 125;
const unsigned int __OBJGROUP_SCROLL_OUVERT	      		= 126;
const unsigned int __OBJGROUP_SCROLL_BLUE	      			= 127;
const unsigned int __OBJGROUP_LIVRE_OUVERT	      		= 128;
const unsigned int __OBJGROUP_LIVRE_OUVERT_EPAIS      	= 129;
const unsigned int __OBJGROUP_WOODEN_DOOR_CLOSED_I       = 130;
const unsigned int __OBJGROUP_WOODEN_DOOR_OPENED_I       = 131;
const unsigned int __OBJGROUP_WOODEN_CHAIR_I	      		= 132; 
const unsigned int __OBJGROUP_WOODEN_CHAIR_2_I	      	= 133; 
const unsigned int __OBJGROUP_WOODEN_ROUND_CHAIR_2_I     = 134; 
const unsigned int __OBJGROUP_2_WOODEN_CHAIR		      	= 135; //(shito 3)
const unsigned int __OBJGROUP_2_WOODEN_CHAIR_2		      = 136; //(shtio 4)
const unsigned int __OBJGROUP_2_WOODEN_ROUND_CHAIR_2     = 137; //(shito 5)
const unsigned int __OBJGROUP_2_WOODEN_CHAIR_I		      = 138; 
const unsigned int __OBJGROUP_2_WOODEN_CHAIR_2_I	      = 139; 
const unsigned int __OBJGROUP_2_WOODEN_ROUND_CHAIR_2_I   = 140; 
const unsigned int __OBJGROUP_POUCH                      = 141;
const unsigned int __OBJGROUP_ROPE                       = 142;
const unsigned int __OBJGROUP_STUFFED_BASKET_1           = 143;
const unsigned int __OBJGROUP_STUFFED_BASKET_2           = 144;
const unsigned int __OBJGROUP_STUFFED_BASKET_3           = 145;
const unsigned int __OBJGROUP_FRUIT_1                    = 146;
const unsigned int __OBJGROUP_FRUIT_2                    = 147;
const unsigned int __OBJGROUP_FRUIT_3                    = 148;
const unsigned int __OBJGROUP_FRUIT_4                    = 149;
const unsigned int __OBJGROUP_FRUIT_5                    = 150;
const unsigned int __OBJGROUP_FRUIT_6                    = 151;
const unsigned int __OBJGROUP_FRUIT_7                    = 152;
const unsigned int __OBJGROUP_FRUIT_8                    = 153;
const unsigned int __OBJGROUP_FRUIT_9                    = 154;
const unsigned int __OBJGROUP_FRUIT_10                   = 155;
const unsigned int __OBJGROUP_FRUIT_11                   = 156;
const unsigned int __OBJGROUP_FRUIT_12                   = 157;
const unsigned int __OBJGROUP_FRUIT_13                   = 158;
const unsigned int __OBJGROUP_FRUIT_14                   = 159;
const unsigned int __OBJGROUP_COINS                      = 160;
const unsigned int __OBJGROUP_COINS_PILE                 = 161;
const unsigned int __OBJGROUP_COINS_BIG_PILE             = 162;
const unsigned int __OBJGROUP_BATWINGS                   = 163;
const unsigned int __OBJGROUP_GEMS_PURPLE                = 164;
const unsigned int __OBJGROUP_GEMS_YELLOW                = 165;
const unsigned int __OBJGROUP_GEMS_BLUE                  = 166;
const unsigned int __OBJGROUP_GEMS_GREEN                 = 167;
const unsigned int __OBJGROUP_GEMS_PACK_1                = 168;
const unsigned int __OBJGROUP_GEMS_PACK_2                = 169;
const unsigned int __OBJGROUP_GEMS_PACK_3                = 170;
const unsigned int __OBJGROUP_KOBOLDHAIR                 = 171;      
const unsigned int __OBJGROUP_NECKLACE_1                 = 172;
const unsigned int __OBJGROUP_NECKLACE_2                 = 173;
const unsigned int __OBJGROUP_NECKLACE_3                 = 174;
const unsigned int __OBJGROUP_ORCFEET                    = 175;
const unsigned int __OBJGROUP_RINGS_1                    = 176;
const unsigned int __OBJGROUP_RINGS_2                    = 177;
const unsigned int __OBJGROUP_RINGS_3                    = 178;  
const unsigned int __OBJGROUP_RINGS_4                    = 179;
const unsigned int __OBJGROUP_RINGS_5                    = 180;
const unsigned int __OBJGROUP_SKEL_BONE                  = 181;
const unsigned int __OBJGROUP_SPIDER_EYES                = 182;
const unsigned int __OBJGROUP_PADDED_GLOVE               = 183;
const unsigned int __OBJGROUP_PADDED_HELM                = 184;
const unsigned int __OBJGROUP_PADDED_ARMOR               = 185;
const unsigned int __OBJGROUP_PADDED_SLEEVES             = 186;
const unsigned int __OBJGROUP_PADDED_LEGGINGS            = 187;
const unsigned int __OBJGROUP_SCALE_ARMOR                = 188;
const unsigned int __OBJGROUP_LEVIER                     = 189;
const unsigned int __OBJGROUP_FIRECAMP                   = 190;
const unsigned int __OBJGROUP_CAMPBURNT                  = 201;
const unsigned int __OBJGROUP_GLINTING_SWORD             = 202;
const unsigned int __OBJGROUP_DESTINY_GEM                = 203;
const unsigned int __OBJGROUP_VOLCANO_ROCK               = 204;
const unsigned int __OBJGROUP_RING_HELM                  = 205;
const unsigned int __OBJGROUP_RING_ARMOR                 = 206;
const unsigned int __OBJGROUP_RING_ARMOR_SLEEVES         = 207;
const unsigned int __OBJGROUP_RING_LEGGINGS              = 208;
const unsigned int __OBJGROUP_FEATHER                    = 209;
const unsigned int __OBJGROUP_ICESHARD                   = 210;
const unsigned int __OBJGROUP_LIFEGEM                    = 211;
const unsigned int __OBJGROUP_OAKTREELEAF                = 212;
const unsigned int __OBJGROUP_PADDED_BOOTS               = 213;
const unsigned int __OBJGROUP_TORCHE                     = 214;
const unsigned int __OBJGROUP_TORCHE_I                   = 215;
const unsigned int __OBJGROUP_BELT                       = 235;
const unsigned int __OBJGROUP_BLUEFLASK                  = 236;
const unsigned int __OBJGROUP_BRACELET                   = 237;
const unsigned int __OBJGROUP_CHEST2                     = 238;
const unsigned int __OBJGROUP_PINKLEAF                   = 239;
const unsigned int __OBJGROUP_POT_GREEN                  = 240;
const unsigned int __OBJGROUP_POT_RED                    = 241;
const unsigned int __OBJGROUP_SHIELD                     = 242;
const unsigned int __OBJGROUP_STONELIFE                  = 243;
const unsigned int __OBJGROUP_TORCH2                     = 244;
const unsigned int __OBJGROUP_TOOTH                      = 245;
const unsigned int __OBJGROUP_GODPOT_BLUE				      = 246;
const unsigned int __OBJGROUP_GODPOT_GREEN				   = 247;
const unsigned int __OBJGROUP_GODPOT_RED 				      = 248;
const unsigned int __OBJGROUP_GODPOT_YELLOW				   = 249;
const unsigned int __OBJGROUP_LARGEPOT_GREEN			      = 250;
const unsigned int __OBJGROUP_LARGEPOT_RED  			      = 251;
const unsigned int __OBJGROUP_POT_BLUE					      = 252;
const unsigned int __OBJGROUP_POT_ORANGE				      = 253;
const unsigned int __OBJGROUP_POT_TURQUOISE				   = 254;
const unsigned int __OBJGROUP_POT_VIOLET				      = 255;
const unsigned int __OBJGROUP_POT_YELLOW				      = 256;
const unsigned int __OBJGROUP_GREENFLASK				      = 257;
const unsigned int __OBJGROUP_REDFLASK					      = 258;
const unsigned int __OBJGROUP_LEATHER_GLOVE			      = 259;
const unsigned int __OBJGROUP_LEATHER_BOOTS	  		      = 260;
const unsigned int __OBJGROUP_LEATHER_PANTS	  		      = 261;
const unsigned int __OBJGROUP_PLATE_ARMOR	      		   = 262;
const unsigned int __OBJGROUP_PLATE_GLOVE	      		   = 263;
const unsigned int __OBJGROUP_PLATE_ARMOR_W_SLEEVE		   = 264;
const unsigned int __OBJGROUP_PLATE_BOOT	      		   = 265;
const unsigned int __OBJGROUP_PLATE_LEGS	      		   = 266;
const unsigned int __OBJGROUP_PLATE_HELM	      		   = 267;
const unsigned int __OBJGROUP_CHAIN_LEGS				      = 268;
const unsigned int __OBJGROUP_CHAIN_BODY				      = 269;
const unsigned int __OBJGROUP_CHAIN_COIF				      = 270;
const unsigned int __OBJGROUP_DARK_SWORD				      = 271;
const unsigned int __OBJGROUP_ROMAN_SHIELD			      = 272;
const unsigned int __OBJGROUP_BAROSSA_SHIELD			      = 273;
const unsigned int __OBJGROUP_DAGGER      		      	= 274;
const unsigned int __OBJGROUP_REAL_DARKSWORD			      = 275;
const unsigned int __OBJGROUP_HORNED_HELMET			      = 276;
const unsigned int __OBJGROUP_BATTLE_SWORD			      = 277;
const unsigned int __OBJGROUP_NECROMANROBE			      = 278;
const unsigned int __OBJGROUP_GOLDENCROWN				      = 279;
const unsigned int __OBJGROUP_GOLDEN_STAR				      = 280;
const unsigned int __OBJGROUP_ELVEN_HAT				      = 281;
const unsigned int __OBJGROUP_ORC_SHIELD				      = 282;
const unsigned int __OBJGROUP_STUDDEDARMOR			      = 283;
const unsigned int __OBJGROUP_LEG_CLOTH1				      = 284;
const unsigned int __OBJGROUP_BODY_CLOTH1				      = 285;
const unsigned int __OBJGROUP_STUDDEDLEG				      = 286;
const unsigned int __OBJGROUP_REDCAPE					      = 287;
const unsigned int __OBJGROUP_BLACKLEATHER_BOOT		      = 288;
const unsigned int __OBJGROUP_HEAD                       = 289;
const unsigned int __OBJGROUP_SUNDIAL_TALK               = 290;
const unsigned int __OBJGROUP_SIGN1_TALK                 = 291;
const unsigned int __OBJGROUP_SIGN2_TALK                 = 292;
const unsigned int __OBJGROUP_SIGN3_TALK                 = 293;
const unsigned int __OBJGROUP_STAFF2			      		= 294;
const unsigned int __OBJGROUP_STAFF3			      		= 295;
const unsigned int __OBJGROUP_STAFF4			      		= 296;
const unsigned int __OBJGROUP_PORTAL   		      		= 297;
const unsigned int __OBJGROUP_VAULT_TALK                 = 323;
const unsigned int __OBJGROUP_FOUGERE                    = 324;
const unsigned int __OBJGROUP_KRAANIAN_EGG               = 325;
const unsigned int __OBJGROUP_WOLF_PELT                  = 326;
const unsigned int __OBJGROUP_VAULT_TALK_I               = 327;
const unsigned int __OBJGROUP_HUMAN_FOOT                 = 328;
const unsigned int __OBJGROUP_TROLLBADGE                 = 329;
const unsigned int __OBJGROUP_SHOP_INN   		      		= 330;
const unsigned int __OBJGROUP_SHOP_POTION 	      		= 347;
const unsigned int __OBJGROUP_SHOP_PAWN   	      		= 360;
const unsigned int __OBJGROUP_SHOP_ARMOR 	         		= 373;
const unsigned int __OBJGROUP_SHOP_WEAPON 	      		= 390;
const unsigned int __OBJGROUP_SHOP_INN_I   		      	= 331;
const unsigned int __OBJGROUP_SHOP_POTION_I 	      		= 348;
const unsigned int __OBJGROUP_SHOP_PAWN_I   	      		= 361;
const unsigned int __OBJGROUP_SHOP_ARMOR_I 	         	= 374;
const unsigned int __OBJGROUP_SHOP_WEAPON_I 	      		= 391;
const unsigned int __OBJGROUP_LARGE_BOW                  = 421;
const unsigned int __OBJGROUP_QUIVER                     = 422;
const unsigned int __OBJGROUP_REDROBE			            = 423;
const unsigned int __OBJGROUP_MAGEROBE			            = 424;
const unsigned int __OBJGROUP_WHITEROBE			         = 425;
const unsigned int __OBJGROUP_CHEST_TROLL 	      		= 426;
const unsigned int __OBJGROUP_WHIRLPOOL_GREEN            = 427;
const unsigned int __OBJGROUP_OGRECLUB                   = 447;
const unsigned int __OBJGROUP_LARGE_BOW2                = 448;
const unsigned int __OBJGROUP_FANCY_SHORT_BOW           = 449;
const unsigned int __OBJGROUP_FANCY_LONG_BOW            = 450;
const unsigned int __OBJGROUP_BLUE_QUIVER               = 451;
const unsigned int __OBJGROUP_YELLOW_QUIVER             = 452;
const unsigned int __OBJGROUP_GREEN_QUIVER              = 453;
const unsigned int __OBJGROUP_RED_QUIVER                = 454;
const unsigned int __OBJGROUP_BLACK_QUIVER              = 455;
const unsigned int __OBJGROUP_DOOR_TALK                 = 456;
const unsigned int __OBJGROUP_DOOR_TALK_I               = 457;
const unsigned int __OBJGROUP_VAULT                     = 458;
const unsigned int __OBJGROUP_VAULT_I                   = 459;
const unsigned int __OBJGROUP_CENTAUR_SHIELD1           = 460;
const unsigned int __OBJGROUP_CENTAUR_SHIELD2           = 461;
const unsigned int __OBJGROUP_SHAMAN_HELM               = 462;
const unsigned int __OBJGROUP_SKAVEN_CLUB               = 463;
const unsigned int __OBJGROUP_SKAVEN_KNIFE              = 464;
const unsigned int __OBJGROUP_SKAVEN_SHIELD1            = 465;
const unsigned int __OBJGROUP_SKAVEN_SHIELD2            = 466;
const unsigned int __OBJGROUP_SKAVEN_SHIELD3            = 467;
const unsigned int __OBJGROUP_SKELETON_AXE              = 468;
const unsigned int __OBJGROUP_SKELETON_HELM             = 469;
const unsigned int __OBJGROUP_SKELETON_SHIELD           = 470;
const unsigned int __OBJGROUP_SKELETON_SWORD            = 471;
const unsigned int __OBJGROUP_SERAPH_BLACK_WINGS        = 472;
const unsigned int __OBJGROUP_SERAPH_WHITE_WINGS        = 473;
const unsigned int __OBJGROUP_DARK_GEM                  = 474;
const unsigned int __OBJGROUP_PURPLE_GEM                = 475;
const unsigned int __OBJGROUP_RED_GEM                   = 476;
const unsigned int __OBJGROUP_WHIRLPOOL_EARTH           = 477;
const unsigned int __OBJGROUP_COFFIN_TALK               = 497;
const unsigned int __OBJGROUP_HALBERD                   = 498;
const unsigned int __OBJGROUP_SMALL_PURPLE_GEM          = 499;
const unsigned int __OBJGROUP_SMALL_RED_GEM             = 500;
const unsigned int __OBJGROUP_CAULDRON                  = 501;
const unsigned int __OBJGROUP_CAULDRON_GROUND           = 522;
const unsigned int __OBJGROUP_SKAVEN_CORPSE1            = 543;
const unsigned int __OBJGROUP_SKAVEN_CORPSE2            = 544;
const unsigned int __OBJGROUP_SKAVEN_CORPSE3            = 545;
const unsigned int __OBJGROUP_SKAVEN_CORPSE4            = 546;
const unsigned int __OBJGROUP_SKAVEN_CORPSE_I1          = 547;
const unsigned int __OBJGROUP_SKAVEN_CORPSE_I2          = 548;
const unsigned int __OBJGROUP_SKAVEN_CORPSE_I3          = 549;
const unsigned int __OBJGROUP_SKAVEN_CORPSE_I4          = 550;
const unsigned int __OBJGROUP_RIBCAGE					= 551;
const unsigned int __OBJGROUP_HEART						= 552;

// New added by Dialsoft - BEGIN
const unsigned int __OBJGROUP_BRACELET_RUBIS			= 553;
const unsigned int __OBJGROUP_BELT_JEWELS_BROWN			= 554;
const unsigned int __OBJGROUP_BELT_JEWELS_PURPLE		= 555;
const unsigned int __OBJGROUP_BELT_RED					= 556;
const unsigned int __OBJGROUP_BRACELET_AZURE			= 557;
const unsigned int __OBJGROUP_BRACELET_SQUARE_WHITE		= 558;
const unsigned int __OBJGROUP_GEM_AZURE					= 559;
const unsigned int __OBJGROUP_GEM_ORANGE				= 560;
const unsigned int __OBJGROUP_GEM_PINK					= 561;
const unsigned int __OBJGROUP_RING_3RUBIS				= 562;
const unsigned int __OBJGROUP_RING_RED					= 563;
const unsigned int __OBJGROUP_RING_STARGOLD				= 564;
const unsigned int __OBJGROUP_MASQUE_GOBLIN				= 565;
const unsigned int __OBJGROUP_RING_CUT_GREEN			= 566;
const unsigned int __OBJGROUP_RING_CUT_RED				= 567;
const unsigned int __OBJGROUP_RUBIS_FOCUS				= 568;
const unsigned int __OBJGROUP_DIAMOND_FOCUS				= 569;
const unsigned int __OBJGROUP_EMERALD_FOCUS				= 570;
const unsigned int __OBJGROUP_EYE_OF_TIGER				= 571;
const unsigned int __OBJGROUP_SAPHIRE_FOCUS				= 572;
const unsigned int __OBJGROUP_MANA_STONE				= 573;
const unsigned int __OBJGROUP_BLUE_STONE				= 574;
const unsigned int __OBJGROUP_REDFEATHER				= 575;
const unsigned int __OBJGROUP_FIREFLAIL					= 576;
const unsigned int __OBJGROUP_SPIKEDLEATHER				= 577;
const unsigned int __OBJGROUP_DARKWINGS					= 578;
const unsigned int __OBJGROUP_SERAPH_NEUTRAL_WINGS		= 579;
const unsigned int __OBJGROUP_SERAPH_RED_WINGS			= 580;
const unsigned int __OBJGROUP_SERAPH_GOLD_WINGS			= 581;
const unsigned int __OBJGROUP_SERAPH_DARKRED_WINGS		= 582;
const unsigned int __OBJGROUP_SERAPH_DARKGOLD_WINGS		= 583;
const unsigned int __OBJGROUP_SERAPH_LIGHTBLUE_WINGS	= 584;
const unsigned int __OBJGROUP_SERAPH_ORANGE_WINGS		= 585;
const unsigned int __OBJGROUP_FWHITEROBE_BLUE			= 586;
const unsigned int __OBJGROUP_FWHITEROBE_GREEN			= 587;
const unsigned int __OBJGROUP_FWHITEROBE_DARKBLUE		= 588;
const unsigned int __OBJGROUP_FWHITEROBE_VIOLET			= 589;
const unsigned int __OBJGROUP_FWHITEROBE_PURPLE			= 590;
const unsigned int __OBJGROUP_FWHITEROBE_YELLOW			= 591;
const unsigned int __OBJGROUP_FWHITEROBE_GRAY			= 592;
const unsigned int __OBJGROUP_FWHITEROBE_MAUVE			= 593;
const unsigned int __OBJGROUP_FWHITEROBE_ORANGE			= 594;
const unsigned int __OBJGROUP_FWHITEROBE_BRUN			= 595;
const unsigned int __OBJGROUP_FWHITEROBE_DARK			= 596;
//Added by Tiamat
const unsigned int __OBJGROUP_PLATE_ARMOR_GOLD	        = 597;
const unsigned int __OBJGROUP_PLATE_GLOVE_GOLD	      	= 598;
const unsigned int __OBJGROUP_PLATE_ARMOR_W_SLEEVE_GOLD	= 599;
const unsigned int __OBJGROUP_PLATE_BOOT_GOLD	      	= 600;
const unsigned int __OBJGROUP_PLATE_LEGS_GOLD	      	= 601;
const unsigned int __OBJGROUP_PLATE_HELM_GOLD	      	= 602;
const unsigned int __OBJGROUP_PLATE_ARMOR_SILVER        = 603;
const unsigned int __OBJGROUP_PLATE_GLOVE_SILVER      	= 604;
const unsigned int __OBJGROUP_PLATE_ARMOR_W_SLEEVE_SILVER	= 605;
const unsigned int __OBJGROUP_PLATE_BOOT_SILVER	      	= 606;
const unsigned int __OBJGROUP_PLATE_LEGS_SILVER	      	= 607;
const unsigned int __OBJGROUP_PLATE_HELM_SILVER	      	= 608;
const unsigned int __OBJGROUP_PLATE_ARMOR_BLACK	        = 609;
const unsigned int __OBJGROUP_PLATE_GLOVE_BLACK      	= 610;
const unsigned int __OBJGROUP_PLATE_ARMOR_W_SLEEVE_BLACK	= 611;
const unsigned int __OBJGROUP_PLATE_BOOT_BLACK	      	= 612;
const unsigned int __OBJGROUP_PLATE_LEGS_BLACK	      	= 613;
const unsigned int __OBJGROUP_PLATE_HELM_BLACK	      	= 614;
const unsigned int __OBJGROUP_PLATE_ARMOR_BLUE        = 615;
const unsigned int __OBJGROUP_PLATE_GLOVE_BLUE      	= 616;
const unsigned int __OBJGROUP_PLATE_ARMOR_W_SLEEVE_BLUE	= 617;
const unsigned int __OBJGROUP_PLATE_BOOT_BLUE	      	= 618;
const unsigned int __OBJGROUP_PLATE_LEGS_BLUE	      	= 619;
const unsigned int __OBJGROUP_PLATE_HELM_BLUE	      	= 620;
const unsigned int __OBJGROUP_PLATE_ARMOR_GREEN        = 621;
const unsigned int __OBJGROUP_PLATE_GLOVE_GREEN      	= 622;
const unsigned int __OBJGROUP_PLATE_ARMOR_W_SLEEVE_GREEN	= 623;
const unsigned int __OBJGROUP_PLATE_BOOT_GREEN	      	= 624;
const unsigned int __OBJGROUP_PLATE_LEGS_GREEN	      	= 625;
const unsigned int __OBJGROUP_PLATE_HELM_GREEN	      	= 626;
const unsigned int __OBJGROUP_PLATE_ARMOR_RED	        = 627;
const unsigned int __OBJGROUP_PLATE_GLOVE_RED	      	= 628;
const unsigned int __OBJGROUP_PLATE_ARMOR_W_SLEEVE_RED	= 629;
const unsigned int __OBJGROUP_PLATE_BOOT_RED	      	= 630;
const unsigned int __OBJGROUP_PLATE_LEGS_RED	      	= 631;
const unsigned int __OBJGROUP_PLATE_HELM_RED	      	= 632;
const unsigned int __OBJGROUP_PLATE_ARMOR_PURPLE        = 633;
const unsigned int __OBJGROUP_PLATE_GLOVE_PURPLE      	= 634;
const unsigned int __OBJGROUP_PLATE_ARMOR_W_SLEEVE_PURPLE	= 635;
const unsigned int __OBJGROUP_PLATE_BOOT_PURPLE	      	= 636;
const unsigned int __OBJGROUP_PLATE_LEGS_PURPLE	      	= 637;
const unsigned int __OBJGROUP_PLATE_HELM_PURPLE	      	= 638;
const unsigned int __OBJGROUP_PLATE_ARMOR_EMERALD        = 639;
const unsigned int __OBJGROUP_PLATE_GLOVE_EMERALD    	= 640;
const unsigned int __OBJGROUP_PLATE_ARMOR_W_SLEEVE_EMERALD	= 641;
const unsigned int __OBJGROUP_PLATE_BOOT_EMERALD	      	= 642;
const unsigned int __OBJGROUP_PLATE_LEGS_EMERALD	      	= 643;
const unsigned int __OBJGROUP_PLATE_HELM_EMERALD	      	= 644;
const unsigned int __OBJGROUP_ORGUE							= 645;
const unsigned int __OBJGROUP_TIGERAXE						= 646;
const unsigned int __OBJGROUP_ANCIENTAXE					= 647;
const unsigned int __OBJGROUP_FLOWERS						= 648;
const unsigned int __OBJGROUP_NECROSTAFF					= 649;
// some static sprites being able to be summoed :
const unsigned int __OBJGROUP_TREE1							= 650;
const unsigned int __OBJGROUP_GREENCAPE					= 651;
const unsigned int __OBJGROUP_YELLOWCAPE					= 652;
const unsigned int __OBJGROUP_SILVERCAPE					= 653;
const unsigned int __OBJGROUP_PURPLECAPE					= 654;
const unsigned int __OBJGROUP_BLACKCAPE					= 655;
const unsigned int __OBJGROUP_AQUACAPE					= 656;
const unsigned int __OBJGROUP_BLUECAPE					= 657;

const unsigned int __OBJGROUP_WITCH_HAT1           = 658;
const unsigned int __OBJGROUP_WITCH_HAT2           = 659;
const unsigned int __OBJGROUP_WITCH_HAT3           = 660;
const unsigned int __OBJGROUP_NEW_BOW01            = 661;
const unsigned int __OBJGROUP_DWARF_HAMMER         = 662;
const unsigned int __OBJGROUP_AXE_DESTRUCTION      = 663;
const unsigned int __OBJGROUP_SWORD_ANGEL          = 664;
const unsigned int __OBJGROUP_CLAY2BLADES          = 665;
const unsigned int __OBJGROUP_SWORD_HERO           = 666;
const unsigned int __OBJGROUP_BUTTERFLY_WING1      = 667;
const unsigned int __OBJGROUP_BUTTERFLY_WING2      = 668;
const unsigned int __OBJGROUP_BUTTERFLY_WING3      = 669;
const unsigned int __OBJGROUP_BUTTERFLY_WING4      = 670;
const unsigned int __OBJGROUP_HAMM                 = 671;
const unsigned int __OBJGROUP_ARCHWINGS_WHITE      = 672;
const unsigned int __OBJGROUP_LICHROBE     	      = 673;
const unsigned int __OBJGROUP_ARMORED_ROBE  	      = 674;
const unsigned int __OBJGROUP_NOEL_HAT             = 675;
const unsigned int __OBJGROUP_ORC_SHIELD2          = 676;
const unsigned int __OBJGROUP_SK_SHIELD            = 677;

const unsigned int __OBJGROUP_V2_HAUME01           = 680;
const unsigned int __OBJGROUP_V2_HAUME02           = 681;
const unsigned int __OBJGROUP_V2_HAUME03           = 682;
const unsigned int __OBJGROUP_V2_HAUME04           = 683;
const unsigned int __OBJGROUP_V2_HAT01             = 684;
const unsigned int __OBJGROUP_V2_MASK01            = 685;

const unsigned int __OBJGROUP_V2_DAGGER_VIP        = 686;
const unsigned int __OBJGROUP_V2_DAGGER01          = 687;
const unsigned int __OBJGROUP_V2_DAGGER02          = 688;
const unsigned int __OBJGROUP_V2_DAGGER03          = 689;
const unsigned int __OBJGROUP_V2_DAGGER04          = 690;
const unsigned int __OBJGROUP_V2_DAGGER05          = 691;

//NM_TAG_ADD_SWORD
const unsigned int __OBJGROUP_V2_BUSSWORD01        = 692;
const unsigned int __OBJGROUP_V2_BUSSWORD02        = 693;
const unsigned int __OBJGROUP_V2_BUSSWORD03        = 694;
const unsigned int __OBJGROUP_V2_CLAYSWORD01       = 695;
const unsigned int __OBJGROUP_V2_CLAYSWORD02       = 696;
const unsigned int __OBJGROUP_V2_GLAIVESWORD01     = 697;
const unsigned int __OBJGROUP_V2_GLAIVESWORD02     = 698;
const unsigned int __OBJGROUP_V2_SWORD01           = 699;
const unsigned int __OBJGROUP_V2_SWORD02           = 700;
const unsigned int __OBJGROUP_V2_SWORD03           = 701;
const unsigned int __OBJGROUP_V2_SWORD04           = 702;
const unsigned int __OBJGROUP_V2_SWORD05           = 703;
const unsigned int __OBJGROUP_V2_SWORD06           = 704;
const unsigned int __OBJGROUP_V2_SWORD07           = 705;
const unsigned int __OBJGROUP_V2_SWORD08           = 706;
const unsigned int __OBJGROUP_V2_2BUSSWORD01       = 707;
const unsigned int __OBJGROUP_V2_2BUSSWORD02       = 708;
const unsigned int __OBJGROUP_V2_2BUSSWORD03       = 709;
const unsigned int __OBJGROUP_V2_2CLAYSWORD01      = 710;
const unsigned int __OBJGROUP_V2_2CLAYSWORD02      = 711;
const unsigned int __OBJGROUP_V2_2GLAIVESWORD01    = 712;
const unsigned int __OBJGROUP_V2_2GLAIVESWORD02    = 713;
const unsigned int __OBJGROUP_V2_2SWORD01          = 714;
const unsigned int __OBJGROUP_V2_2SWORD02          = 715;
const unsigned int __OBJGROUP_V2_2SWORD03          = 716;
const unsigned int __OBJGROUP_V2_2SWORD04          = 717;
const unsigned int __OBJGROUP_V2_2SWORD05          = 718;
const unsigned int __OBJGROUP_V2_2SWORD06          = 719;
const unsigned int __OBJGROUP_V2_2SWORD07          = 720;
const unsigned int __OBJGROUP_V2_2SWORD08          = 721;
const unsigned int __OBJGROUP_V2_HACHE01           = 722;
const unsigned int __OBJGROUP_V2_HACHE02           = 723;
const unsigned int __OBJGROUP_V2_HACHE03           = 724;
const unsigned int __OBJGROUP_V2_HACHE04           = 725;
const unsigned int __OBJGROUP_V2_HACHE05           = 726;
const unsigned int __OBJGROUP_V2_HACHE06           = 727;
const unsigned int __OBJGROUP_V2_HACHE07           = 728;
const unsigned int __OBJGROUP_V2_HACHE08           = 729;
const unsigned int __OBJGROUP_V2_HACHE09           = 730;
const unsigned int __OBJGROUP_V2_HACHE10           = 731;
const unsigned int __OBJGROUP_V2_HACHE11           = 732;
const unsigned int __OBJGROUP_V2_2HACHE01          = 733;
const unsigned int __OBJGROUP_V2_2HACHE02          = 734;
const unsigned int __OBJGROUP_V2_2HACHE03          = 735;
const unsigned int __OBJGROUP_V2_2HACHE04          = 736;
const unsigned int __OBJGROUP_V2_2DAGGER01         = 737;
const unsigned int __OBJGROUP_V2_2DAGGER02         = 738;
const unsigned int __OBJGROUP_V2_2DAGGER03         = 739;
const unsigned int __OBJGROUP_V2_2DAGGER04         = 740;
const unsigned int __OBJGROUP_V2_2DAGGER05         = 741;
const unsigned int __OBJGROUP_V2_2DAGGER06         = 742;
const unsigned int __OBJGROUP_V2_BOW01             = 743;
const unsigned int __OBJGROUP_V2_BOW02             = 744;
const unsigned int __OBJGROUP_V2_BOW03             = 745;
const unsigned int __OBJGROUP_V2_BOW04             = 746;
const unsigned int __OBJGROUP_V2_BOW05             = 747;
const unsigned int __OBJGROUP_V2_BOW06             = 748;
const unsigned int __OBJGROUP_V2_BOW07             = 749;
const unsigned int __OBJGROUP_V2_BOW08             = 750;
const unsigned int __OBJGROUP_V2_BOW09             = 751;
const unsigned int __OBJGROUP_V2_BOW10             = 752;
const unsigned int __OBJGROUP_V2_SCEPTRE01         = 753;
const unsigned int __OBJGROUP_V2_SCEPTRE02         = 754;
const unsigned int __OBJGROUP_V2_SCEPTRE03         = 755;
const unsigned int __OBJGROUP_V2_SP01              = 756;
const unsigned int __OBJGROUP_V2_SP02              = 757;
const unsigned int __OBJGROUP_V2_SP03              = 758;
const unsigned int __OBJGROUP_V2_SP04              = 759;
const unsigned int __OBJGROUP_V2_SP05              = 760;
const unsigned int __OBJGROUP_V2_SP06              = 761;
const unsigned int __OBJGROUP_V2_SP07              = 762;
const unsigned int __OBJGROUP_V2_2SP01             = 763;
const unsigned int __OBJGROUP_V2_2SP02             = 764;
const unsigned int __OBJGROUP_V2_2SP03             = 765;
const unsigned int __OBJGROUP_V2_2SP04             = 766;
const unsigned int __OBJGROUP_V2_2SP05             = 767;
const unsigned int __OBJGROUP_V2_2SP06             = 768;

const unsigned int __OBJGROUP_WOODEN_DOOR2_CLOSED  = 769; //door2 1
const unsigned int __OBJGROUP_WOODEN_DOOR2_OPENED  = 770; //door2 11
const unsigned int __OBJGROUP_WOODEN_DOOR2_CLOSED_I= 771;
const unsigned int __OBJGROUP_WOODEN_DOOR2_OPENED_I= 772;
const unsigned int __OBJGROUP_WOODEN_DOOR2_ANIM02  = 773;
const unsigned int __OBJGROUP_WOODEN_DOOR2_ANIM03  = 774;
const unsigned int __OBJGROUP_WOODEN_DOOR2_ANIM04  = 775;
const unsigned int __OBJGROUP_WOODEN_DOOR2_ANIM05  = 776;
const unsigned int __OBJGROUP_WOODEN_DOOR2_ANIM06  = 777;
const unsigned int __OBJGROUP_WOODEN_DOOR2_ANIM07  = 778;
const unsigned int __OBJGROUP_WOODEN_DOOR2_ANIM08  = 779;
const unsigned int __OBJGROUP_WOODEN_DOOR2_ANIM09  = 780;
const unsigned int __OBJGROUP_WOODEN_DOOR2_ANIM10  = 781;

const unsigned int __OBJGROUP_V2_HAMMER01          = 782;
const unsigned int __OBJGROUP_V2_HAMMER02          = 783;
const unsigned int __OBJGROUP_V2_HAMMER03          = 784;
const unsigned int __OBJGROUP_V2_HAMMER04          = 785;
const unsigned int __OBJGROUP_V2_HAMMER05          = 786;
const unsigned int __OBJGROUP_V2_HAMMER06          = 787;
const unsigned int __OBJGROUP_V2_HAMMER07          = 788;
const unsigned int __OBJGROUP_V2_2HAMMER01         = 789;
const unsigned int __OBJGROUP_V2_2HAMMER02         = 790;

const unsigned int __OBJGROUP_WOODEN_DOOR3_CLOSED  = 791; //door3 1
const unsigned int __OBJGROUP_WOODEN_DOOR3_OPENED  = 792; //door3 11
const unsigned int __OBJGROUP_WOODEN_DOOR3_CLOSED_I= 793;
const unsigned int __OBJGROUP_WOODEN_DOOR3_OPENED_I= 794;
const unsigned int __OBJGROUP_WOODEN_DOOR3_ANIM02  = 795;
const unsigned int __OBJGROUP_WOODEN_DOOR3_ANIM03  = 796;
const unsigned int __OBJGROUP_WOODEN_DOOR3_ANIM04  = 797;
const unsigned int __OBJGROUP_WOODEN_DOOR3_ANIM05  = 798;
const unsigned int __OBJGROUP_WOODEN_DOOR3_ANIM06  = 799;
const unsigned int __OBJGROUP_WOODEN_DOOR3_ANIM07  = 800;
const unsigned int __OBJGROUP_WOODEN_DOOR3_ANIM08  = 801;
const unsigned int __OBJGROUP_WOODEN_DOOR3_ANIM09  = 802;
const unsigned int __OBJGROUP_WOODEN_DOOR3_ANIM10  = 803;

const unsigned int __OBJGROUP_WOODEN_DOOR4_CLOSED  = 804; //door3 1
const unsigned int __OBJGROUP_WOODEN_DOOR4_OPENED  = 805; //door3 11
const unsigned int __OBJGROUP_WOODEN_DOOR4_CLOSED_I= 806;
const unsigned int __OBJGROUP_WOODEN_DOOR4_OPENED_I= 807;
const unsigned int __OBJGROUP_WOODEN_DOOR4_ANIM02  = 808;
const unsigned int __OBJGROUP_WOODEN_DOOR4_ANIM03  = 809;
const unsigned int __OBJGROUP_WOODEN_DOOR4_ANIM04  = 810;
const unsigned int __OBJGROUP_WOODEN_DOOR4_ANIM05  = 811;
const unsigned int __OBJGROUP_WOODEN_DOOR4_ANIM06  = 812;
const unsigned int __OBJGROUP_WOODEN_DOOR4_ANIM07  = 813;
const unsigned int __OBJGROUP_WOODEN_DOOR4_ANIM08  = 814;
const unsigned int __OBJGROUP_WOODEN_DOOR4_ANIM09  = 815;
const unsigned int __OBJGROUP_WOODEN_DOOR4_ANIM10  = 816;

const unsigned int __OBJGROUP_WOODEN_DOOR5_CLOSED  = 817; //door5 1
const unsigned int __OBJGROUP_WOODEN_DOOR5_OPENED  = 818; //door5 11
const unsigned int __OBJGROUP_WOODEN_DOOR5_CLOSED_I= 819;
const unsigned int __OBJGROUP_WOODEN_DOOR5_OPENED_I= 820;
const unsigned int __OBJGROUP_WOODEN_DOOR5_ANIM02  = 821;
const unsigned int __OBJGROUP_WOODEN_DOOR5_ANIM03  = 822;
const unsigned int __OBJGROUP_WOODEN_DOOR5_ANIM04  = 823;
const unsigned int __OBJGROUP_WOODEN_DOOR5_ANIM05  = 824;
const unsigned int __OBJGROUP_WOODEN_DOOR5_ANIM06  = 825;
const unsigned int __OBJGROUP_WOODEN_DOOR5_ANIM07  = 826;
const unsigned int __OBJGROUP_WOODEN_DOOR5_ANIM08  = 827;
const unsigned int __OBJGROUP_WOODEN_DOOR5_ANIM09  = 828;
const unsigned int __OBJGROUP_WOODEN_DOOR5_ANIM10  = 829;

const unsigned int __OBJGROUP_WOODEN_DOOR6_CLOSED  = 830; //door6 1
const unsigned int __OBJGROUP_WOODEN_DOOR6_OPENED  = 831; //door6 11
const unsigned int __OBJGROUP_WOODEN_DOOR6_CLOSED_I= 832;
const unsigned int __OBJGROUP_WOODEN_DOOR6_OPENED_I= 833;
const unsigned int __OBJGROUP_WOODEN_DOOR6_ANIM02  = 834;
const unsigned int __OBJGROUP_WOODEN_DOOR6_ANIM03  = 835;
const unsigned int __OBJGROUP_WOODEN_DOOR6_ANIM04  = 836;
const unsigned int __OBJGROUP_WOODEN_DOOR6_ANIM05  = 837;
const unsigned int __OBJGROUP_WOODEN_DOOR6_ANIM06  = 838;
const unsigned int __OBJGROUP_WOODEN_DOOR6_ANIM07  = 839;
const unsigned int __OBJGROUP_WOODEN_DOOR6_ANIM08  = 840;
const unsigned int __OBJGROUP_WOODEN_DOOR6_ANIM09  = 841;
const unsigned int __OBJGROUP_WOODEN_DOOR6_ANIM10  = 842;

const unsigned int __OBJGROUP_WOODEN_DOOR7_CLOSED  = 843; //door7 1
const unsigned int __OBJGROUP_WOODEN_DOOR7_OPENED  = 844; //door7 11
const unsigned int __OBJGROUP_WOODEN_DOOR7_CLOSED_I= 845;
const unsigned int __OBJGROUP_WOODEN_DOOR7_OPENED_I= 846;
const unsigned int __OBJGROUP_WOODEN_DOOR7_ANIM02  = 847;
const unsigned int __OBJGROUP_WOODEN_DOOR7_ANIM03  = 848;
const unsigned int __OBJGROUP_WOODEN_DOOR7_ANIM04  = 849;
const unsigned int __OBJGROUP_WOODEN_DOOR7_ANIM05  = 850;
const unsigned int __OBJGROUP_WOODEN_DOOR7_ANIM06  = 851;
const unsigned int __OBJGROUP_WOODEN_DOOR7_ANIM07  = 852;
const unsigned int __OBJGROUP_WOODEN_DOOR7_ANIM08  = 853;
const unsigned int __OBJGROUP_WOODEN_DOOR7_ANIM09  = 854;
const unsigned int __OBJGROUP_WOODEN_DOOR7_ANIM10  = 855;

const unsigned int __OBJGROUP_WOODEN_DOOR8_CLOSED  = 856; //door8 1
const unsigned int __OBJGROUP_WOODEN_DOOR8_OPENED  = 857; //door8 11
const unsigned int __OBJGROUP_WOODEN_DOOR8_CLOSED_I= 858;
const unsigned int __OBJGROUP_WOODEN_DOOR8_OPENED_I= 859;
const unsigned int __OBJGROUP_WOODEN_DOOR8_ANIM02  = 860;
const unsigned int __OBJGROUP_WOODEN_DOOR8_ANIM03  = 861;
const unsigned int __OBJGROUP_WOODEN_DOOR8_ANIM04  = 862;
const unsigned int __OBJGROUP_WOODEN_DOOR8_ANIM05  = 863;
const unsigned int __OBJGROUP_WOODEN_DOOR8_ANIM06  = 864;
const unsigned int __OBJGROUP_WOODEN_DOOR8_ANIM07  = 865;
const unsigned int __OBJGROUP_WOODEN_DOOR8_ANIM08  = 866;
const unsigned int __OBJGROUP_WOODEN_DOOR8_ANIM09  = 867;
const unsigned int __OBJGROUP_WOODEN_DOOR8_ANIM10  = 868;

const unsigned int __OBJGROUP_V2_2HACHE05          = 869;
const unsigned int __OBJGROUP_V2_2HACHE06          = 870;
const unsigned int __OBJGROUP_V2_SHIELD01          = 871;
const unsigned int __OBJGROUP_V2_SHIELD02          = 872;

const unsigned int __OBJGROUP_V2_MASQUE_GOBLIN_ICE = 873;
const unsigned int __OBJGROUP_V2_BOW05_ICE         = 874;

const unsigned int __OBJGROUP_V2_2GLAIVESWORD02_ICE= 875;
const unsigned int __OBJGROUP_V2_GLAIVESWORD02_ICE = 876;



const unsigned int __OBJGROUP_WITCH_HAT4           = 877;
const unsigned int __OBJGROUP_WITCH_HAT5           = 878;

const unsigned int __OBJGROUP_MAN_ARMOR01_BODY_GR  = 879;
const unsigned int __OBJGROUP_MAN_ARMOR01_BODY_BL  = 880;
const unsigned int __OBJGROUP_MAN_ARMOR01_LEGS_GR  = 881;
const unsigned int __OBJGROUP_MAN_ARMOR01_LEGS_BL  = 882;
const unsigned int __OBJGROUP_MAN_ARMOR01_HAND_GR  = 883;
const unsigned int __OBJGROUP_MAN_ARMOR01_HAND_BL  = 884;
const unsigned int __OBJGROUP_MAN_ARMOR01_FOOT_GR  = 885;
const unsigned int __OBJGROUP_MAN_ARMOR01_FOOT_BL  = 886;
const unsigned int __OBJGROUP_V2_HAUME04_BL        = 887;
const unsigned int __OBJGROUP_SERAPH_DECHU_WINGS   = 888;
const unsigned int __OBJGROUP_T4CP_CASQUE          = 889;
const unsigned int __OBJGROUP_T4CP_CASQUETTE       = 890;
const unsigned int __OBJGROUP_T4CP_SHIELD          = 891;
const unsigned int __OBJGROUP_T4CP_MATRAQUE        = 892;
const unsigned int __OBJGROUP_T4CP_BAT             = 893;
const unsigned int __OBJGROUP_T4CP_12              = 894;
const unsigned int __OBJGROUP_V2_ICESHIELD         = 895;
const unsigned int __OBJGROUP_WHITELEATHER_BOOT    = 896;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER	= 897;

const unsigned int __OBJGROUP_DOOR2_TALK           = 898;
const unsigned int __OBJGROUP_DOOR2_TALK_I         = 899;
const unsigned int __OBJGROUP_DOOR3_TALK           = 900;
const unsigned int __OBJGROUP_DOOR3_TALK_I         = 901;
const unsigned int __OBJGROUP_DOOR4_TALK           = 902;
const unsigned int __OBJGROUP_DOOR4_TALK_I         = 903;
const unsigned int __OBJGROUP_DOOR5_TALK           = 904;
const unsigned int __OBJGROUP_DOOR5_TALK_I         = 905;
const unsigned int __OBJGROUP_DOOR6_TALK           = 906;
const unsigned int __OBJGROUP_DOOR6_TALK_I         = 907;
const unsigned int __OBJGROUP_DOOR7_TALK           = 908;
const unsigned int __OBJGROUP_DOOR7_TALK_I         = 909;
const unsigned int __OBJGROUP_DOOR8_TALK           = 910;
const unsigned int __OBJGROUP_DOOR8_TALK_I         = 911;


const unsigned int __OBJGROUP_CAULDRON_CONTAINER_E = 917;
const unsigned int __OBJGROUP_SERAPH_DECHU2_WINGS  = 918;

//NMS Customisation  919 - 1050

const unsigned int __OBJGROUP_SERAPH_NMS_nDECHU_WINGS01  = 919;
const unsigned int __OBJGROUP_SERAPH_NMS_nDECHU_WINGS02  = 920;
const unsigned int __OBJGROUP_SERAPH_NMS_nDECHU_WINGS03  = 921;
const unsigned int __OBJGROUP_SERAPH_DARKWINGS_PINK      = 922;
const unsigned int __OBJGROUP_NEW_LICHROBE       	      = 923;
const unsigned int __OBJGROUP_NEW_LICHROBE_BLACK  	      = 924;
const unsigned int __OBJGROUP_NEW_LICHROBE_WHITE  	      = 925;
const unsigned int __OBJGROUP_NEW_LICHROBE_GOLD  	      = 926;
const unsigned int __OBJGROUP_NEW_LICHROBE_GREEN  	      = 927;
const unsigned int __OBJGROUP_NEW_LICHROBE_KIMONO	      = 928;
const unsigned int __OBJGROUP_NEW_LICHROBE_PINK  	      = 929;
const unsigned int __OBJGROUP_NEW_LICHROBE_RED  	      = 930;

const unsigned int __OBJGROUP_NEW_CAPE_01_C0	   	  	   = 931;
const unsigned int __OBJGROUP_NEW_CAPE_01_C1   	   	  	= 932;
const unsigned int __OBJGROUP_NEW_CAPE_01_C2   	   	  	= 933;
const unsigned int __OBJGROUP_NEW_CAPE_01_C3   	   	  	= 934;
const unsigned int __OBJGROUP_NEW_CAPE_01_C4   	   	  	= 935;
const unsigned int __OBJGROUP_NEW_CAPE_01_C5   	   	  	= 936;
const unsigned int __OBJGROUP_NEW_CAPE_01_C6   	   	  	= 937;
const unsigned int __OBJGROUP_NEW_CAPE_01_C7   	   	  	= 938;
const unsigned int __OBJGROUP_NEW_CAPE_01_C8   	   	  	= 939;

const unsigned int __OBJGROUP_NEW_CAPEGG_01_C0   	   	= 940;
const unsigned int __OBJGROUP_NEW_CAPEGG_01_C1   	   	= 941;
const unsigned int __OBJGROUP_NEW_CAPEGG_01_C2   	   	= 942;
const unsigned int __OBJGROUP_NEW_CAPEGG_01_C3   	   	= 943;
const unsigned int __OBJGROUP_NEW_CAPEGG_01_C4   	   	= 944;
const unsigned int __OBJGROUP_NEW_CAPEGG_01_C5   	   	= 945;
const unsigned int __OBJGROUP_NEW_CAPEGG_01_C6   	   	= 946;
const unsigned int __OBJGROUP_NEW_CAPEGG_01_C7   	   	= 947;
const unsigned int __OBJGROUP_NEW_CAPEGG_01_C8   	   	= 948;

const unsigned int __OBJGROUP_NEW_CAPELL_01_C0   	   	= 949;
const unsigned int __OBJGROUP_NEW_CAPELL_01_C1   	   	= 950;
const unsigned int __OBJGROUP_NEW_CAPELL_01_C2   	   	= 951;
const unsigned int __OBJGROUP_NEW_CAPELL_01_C3   	   	= 952;
const unsigned int __OBJGROUP_NEW_CAPELL_01_C4   	   	= 953;
const unsigned int __OBJGROUP_NEW_CAPELL_01_C5   	   	= 954;
const unsigned int __OBJGROUP_NEW_CAPELL_01_C6   	   	= 955;
const unsigned int __OBJGROUP_NEW_CAPELL_01_C7   	   	= 956;
const unsigned int __OBJGROUP_NEW_CAPELL_01_C8   	   	= 957;
const unsigned int __OBJGROUP_ARCHWINGS_PINK             = 958;
const unsigned int __OBJGROUP_V2_2GLAIVESWORD03_ICE      = 959;
const unsigned int __OBJGROUP_V2_GLAIVESWORD03_ICE       = 960;

const unsigned int __OBJGROUP_CAULDRON_CONTAINER01	      = 1000;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER02	      = 1001;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER03	      = 1002;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER04	      = 1003;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER05	      = 1004;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER06	      = 1005;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER07	      = 1006;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER08	      = 1007;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER09	      = 1008;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER10	      = 1009;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER11	      = 1010;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER12	      = 1011;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER13	      = 1012;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER14	      = 1013;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER15	      = 1014;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER16	      = 1015;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER17	      = 1016;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER18	      = 1017;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER19	      = 1018;
const unsigned int __OBJGROUP_CAULDRON_CONTAINER20	      = 1019;


const unsigned int __OBJGROUP_SKELETON_SHIELD_GOLD          = 1050;
const unsigned int __OBJGROUP_SKELETON_SHIELD_SILVER        = 1051;
const unsigned int __OBJGROUP_SKELETON_SHIELD_BLACK         = 1052;
const unsigned int __OBJGROUP_SKELETON_SHIELD_BLUE          = 1053;
const unsigned int __OBJGROUP_SKELETON_SHIELD_GREEN         = 1054;
const unsigned int __OBJGROUP_SKELETON_SHIELD_RED           = 1055;
const unsigned int __OBJGROUP_SKELETON_SHIELD_PURPLE        = 1056;
const unsigned int __OBJGROUP_SKELETON_SHIELD_EMERALD       = 1057;
const unsigned int __OBJGROUP_SKELETON_SHIELD_ORANGE        = 1058;
const unsigned int __OBJGROUP_PLATE_ARMOR_ORANGE	         = 1059;
const unsigned int __OBJGROUP_PLATE_GLOVE_ORANGE	      	= 1060;
const unsigned int __OBJGROUP_PLATE_ARMOR_W_SLEEVE_ORANGE	= 1061;
const unsigned int __OBJGROUP_PLATE_BOOT_ORANGE	         	= 1062;
const unsigned int __OBJGROUP_PLATE_LEGS_ORANGE	      	   = 1063;
const unsigned int __OBJGROUP_PLATE_HELM_ORANGE	         	= 1064;


const unsigned int __OBJGROUP_TEMPLE_DOOR1_CLOSED		   	= 1065; //door3 1
const unsigned int __OBJGROUP_TEMPLE_DOOR1_OPENED		   	= 1066; //door3 11
const unsigned int __OBJGROUP_TEMPLE_DOOR1_CLOSED_I			= 1067;
const unsigned int __OBJGROUP_TEMPLE_DOOR1_OPENED_I			= 1068;
const unsigned int __OBJGROUP_TEMPLE_DOOR1_ANIM02  	   	= 1069;
const unsigned int __OBJGROUP_TEMPLE_DOOR1_ANIM03  	   	= 1070;
const unsigned int __OBJGROUP_TEMPLE_DOOR1_ANIM04  			= 1071;
const unsigned int __OBJGROUP_TEMPLE_DOOR1_ANIM05  			= 1072;
const unsigned int __OBJGROUP_TEMPLE_DOOR1_ANIM06  	   	= 1073;
const unsigned int __OBJGROUP_TEMPLE_DOOR1_ANIM07  	   	= 1074;
const unsigned int __OBJGROUP_TEMPLE_DOOR1_ANIM08  			= 1075;
const unsigned int __OBJGROUP_TEMPLE_DOOR1_ANIM09  			= 1076;
const unsigned int __OBJGROUP_TEMPLE_DOOR1_ANIM10           = 1077;

const unsigned int __OBJGROUP_HALLOWEEN_HEAD                = 1078;
const unsigned int __OBJGROUP_HALLOWEEN_CHEST1              = 1079;
const unsigned int __OBJGROUP_HALLOWEEN_CHEST2              = 1080;
const unsigned int __OBJGROUP_HALLOWEEN_CHEST3              = 1081;
const unsigned int __OBJGROUP_HALLOWEEN_CHEST4              = 1082;
const unsigned int __OBJGROUP_HALLOWEEN_CHEST5              = 1083;
const unsigned int __OBJGROUP_HALLOWEEN_CHEST6              = 1084;
const unsigned int __OBJGROUP_SABRE_LASER_G                 = 1085;
const unsigned int __OBJGROUP_FIRESWORD01                   = 1086;
const unsigned int __OBJGROUP_SABRE_LASER_R                 = 1087;
const unsigned int __OBJGROUP_FIRESWORD01DUAL               = 1088;
const unsigned int __OBJGROUP_NOEL_CANNE                    = 1089;
const unsigned int __OBJGROUP_NOEL_CANNE_LONGUE             = 1090;
const unsigned int __OBJGROUP_NOEL_SAPIN_CHEST              = 1091;

const unsigned int __OBJGROUP_BARIL_NORMAL                  = 1092;
const unsigned int __OBJGROUP_BARIL_FLIPPED                 = 1093;

//const unsigned int __OBJGROUP_ARMORRACK_NORMAL              = 1094;

const unsigned int __OBJGROUP_NIGHTMAREWINGS            = 1095;
const unsigned int __OBJGROUP_NIGHTMAREBIGWINGS         = 1096;
const unsigned int __OBJGROUP_NIGHTMAREMEDWINGS         = 1097;

const unsigned int __OBJGROUP_ORBE_BLACK     			  = 1098;
const unsigned int __OBJGROUP_ORBE_BLUE      			  = 1099;
const unsigned int __OBJGROUP_ORBE_FIRE      			  = 1100;
const unsigned int __OBJGROUP_ORBE_GOLD      			  = 1101;
const unsigned int __OBJGROUP_ORBE_GREEN     			  = 1102;
const unsigned int __OBJGROUP_ORBE_ORANGE     			  = 1103;
const unsigned int __OBJGROUP_ORBE_PURPLE     			  = 1104;
const unsigned int __OBJGROUP_ORBE_RED       			  = 1105;
const unsigned int __OBJGROUP_ORBE_RED2      			  = 1106;
const unsigned int __OBJGROUP_ORBE_ROSE      			  = 1107;
const unsigned int __OBJGROUP_ORBE_WHITE      			  = 1108;
const unsigned int __OBJGROUP_ORBE_YELLOW      			  = 1109;


const unsigned int __OBJGROUP_MAN_ARMOR01_BODY_GREEN    = 1110;
const unsigned int __OBJGROUP_MAN_ARMOR01_BODY_RED      = 1111;
const unsigned int __OBJGROUP_MAN_ARMOR01_BODY_BLUE     = 1112;
const unsigned int __OBJGROUP_MAN_ARMOR01_BODY_AQUA     = 1113;
const unsigned int __OBJGROUP_MAN_ARMOR01_BODY_GOLD     = 1114;
const unsigned int __OBJGROUP_MAN_ARMOR01_BODY_ORANGE   = 1115;
const unsigned int __OBJGROUP_MAN_ARMOR01_BODY_FIRE     = 1116;

const unsigned int __OBJGROUP_MAN_ARMOR01_LEGS_GREEN    = 1117;
const unsigned int __OBJGROUP_MAN_ARMOR01_LEGS_RED      = 1118;
const unsigned int __OBJGROUP_MAN_ARMOR01_LEGS_BLUE     = 1119;
const unsigned int __OBJGROUP_MAN_ARMOR01_LEGS_AQUA     = 1120;
const unsigned int __OBJGROUP_MAN_ARMOR01_LEGS_GOLD     = 1121;
const unsigned int __OBJGROUP_MAN_ARMOR01_LEGS_ORANGE   = 1122;
const unsigned int __OBJGROUP_MAN_ARMOR01_LEGS_FIRE     = 1123;

const unsigned int __OBJGROUP_MAN_ARMOR01_HAND_GREEN    = 1124;
const unsigned int __OBJGROUP_MAN_ARMOR01_HAND_RED      = 1125;
const unsigned int __OBJGROUP_MAN_ARMOR01_HAND_BLUE     = 1126;
const unsigned int __OBJGROUP_MAN_ARMOR01_HAND_AQUA     = 1127;
const unsigned int __OBJGROUP_MAN_ARMOR01_HAND_GOLD     = 1128;
const unsigned int __OBJGROUP_MAN_ARMOR01_HAND_ORANGE   = 1129;
const unsigned int __OBJGROUP_MAN_ARMOR01_HAND_FIRE     = 1130;

const unsigned int __OBJGROUP_MAN_ARMOR01_FOOT_GREEN    = 1131;
const unsigned int __OBJGROUP_MAN_ARMOR01_FOOT_RED      = 1132;
const unsigned int __OBJGROUP_MAN_ARMOR01_FOOT_BLUE     = 1133;
const unsigned int __OBJGROUP_MAN_ARMOR01_FOOT_AQUA     = 1134;
const unsigned int __OBJGROUP_MAN_ARMOR01_FOOT_GOLD     = 1135;
const unsigned int __OBJGROUP_MAN_ARMOR01_FOOT_ORANGE   = 1136;
const unsigned int __OBJGROUP_MAN_ARMOR01_FOOT_FIRE     = 1137;

const unsigned int __OBJGROUP_V2_HAUME04_GREEN          = 1138;
const unsigned int __OBJGROUP_V2_HAUME04_RED            = 1139;
const unsigned int __OBJGROUP_V2_HAUME04_BLUE           = 1140;
const unsigned int __OBJGROUP_V2_HAUME04_AQUA           = 1141;
const unsigned int __OBJGROUP_V2_HAUME04_GOLD           = 1142;
const unsigned int __OBJGROUP_V2_HAUME04_ORANGE         = 1143;
const unsigned int __OBJGROUP_V2_HAUME04_FIRE           = 1144;
 

const unsigned int __OBJGROUP_NMS_X6WHITE_WINGS         = 1145;
const unsigned int __OBJGROUP_NMS_X6BLACK_WINGS         = 1146;
const unsigned int __OBJGROUP_GAMBLING_MACHINE_L        = 1147;
const unsigned int __OBJGROUP_GAMBLING_MACHINE_R        = 1148;
const unsigned int __OBJGROUP_GHOST_FAUC                = 1149;

const unsigned int __OBJGROUP_LUTIN_RBOOT               = 1150;
const unsigned int __OBJGROUP_LUTIN_GBOOT               = 1151;
const unsigned int __OBJGROUP_OREILLE_LAPIN             = 1152;



const unsigned int __OBJGROUP_NEW_DEBRIT_PIERRE_NPC     = 1157;
const unsigned int __OBJGROUP_NM_DEATH_AXE              = 1158;
const unsigned int __OBJGROUP_SNOWMAN_HAT_BLACK         = 1159;

/*
const unsigned int __OBJGROUP_MINING_CRYSTAL01          = 1160;
const unsigned int __OBJGROUP_MINING_CRYSTAL02          = 1161;
const unsigned int __OBJGROUP_MINING_CRYSTAL03          = 1162;
const unsigned int __OBJGROUP_MINING_CUIVRE01           = 1163;
const unsigned int __OBJGROUP_MINING_CUIVRE02           = 1164;
const unsigned int __OBJGROUP_MINING_CUIVRE03           = 1165;
const unsigned int __OBJGROUP_MINING_EMERAUDE01         = 1166;
const unsigned int __OBJGROUP_MINING_EMERAUDE02         = 1167;
const unsigned int __OBJGROUP_MINING_EMERAUDE03         = 1168;
const unsigned int __OBJGROUP_MINING_FER01              = 1169;
const unsigned int __OBJGROUP_MINING_FER02              = 1170;
const unsigned int __OBJGROUP_MINING_FER03              = 1171;
const unsigned int __OBJGROUP_MINING_GOLD01             = 1172;
const unsigned int __OBJGROUP_MINING_GOLD02             = 1173;
const unsigned int __OBJGROUP_MINING_GOLD03             = 1174;
const unsigned int __OBJGROUP_MINING_RUBIS01            = 1175;
const unsigned int __OBJGROUP_MINING_RUBIS02            = 1176;
const unsigned int __OBJGROUP_MINING_RUBIS03            = 1177;
const unsigned int __OBJGROUP_MINING_SAPHIR01           = 1178;
const unsigned int __OBJGROUP_MINING_SAPHIR02           = 1179;
const unsigned int __OBJGROUP_MINING_SAPHIR03           = 1180;
const unsigned int __OBJGROUP_MINING_SILVER01           = 1181;
const unsigned int __OBJGROUP_MINING_SILVER02           = 1182;
const unsigned int __OBJGROUP_MINING_SILVER03           = 1183;
*/

const unsigned int __OBJGROUP_MINING_DEBRIT_CRYSTAL     = 1184;
const unsigned int __OBJGROUP_MINING_DEBRIT_CUIVRE      = 1185;
const unsigned int __OBJGROUP_MINING_DEBRIT_EMERAUDE    = 1186;
const unsigned int __OBJGROUP_MINING_DEBRIT_FER         = 1187;
const unsigned int __OBJGROUP_MINING_DEBRIT_GOLD        = 1188;
const unsigned int __OBJGROUP_MINING_DEBRIT_RUBIS       = 1189;
const unsigned int __OBJGROUP_MINING_DEBRIT_SAPHIR      = 1190;
const unsigned int __OBJGROUP_MINING_DEBRIT_SILVER      = 1191;




const unsigned int __OBJGROUP_NATURE_ITEMS_01_NPC       = 1200;
const unsigned int __OBJGROUP_NATURE_ITEMS_02_NPC       = 1201;
const unsigned int __OBJGROUP_NATURE_ITEMS_03_NPC       = 1202;
const unsigned int __OBJGROUP_NATURE_ITEMS_04_NPC       = 1203;
const unsigned int __OBJGROUP_NATURE_ITEMS_05_NPC       = 1204;
const unsigned int __OBJGROUP_NATURE_ITEMS_06_NPC       = 1205;
const unsigned int __OBJGROUP_NATURE_ITEMS_07_NPC       = 1206;
const unsigned int __OBJGROUP_NATURE_ITEMS_08_NPC       = 1207;
const unsigned int __OBJGROUP_NATURE_ITEMS_09_NPC       = 1208;
const unsigned int __OBJGROUP_NATURE_ITEMS_10_NPC       = 1209;
const unsigned int __OBJGROUP_NATURE_ITEMS_11_NPC       = 1210;
const unsigned int __OBJGROUP_NATURE_ITEMS_12_NPC       = 1211;
const unsigned int __OBJGROUP_NATURE_ITEMS_13_NPC       = 1212;
const unsigned int __OBJGROUP_NATURE_ITEMS_14_NPC       = 1213;
const unsigned int __OBJGROUP_NATURE_ITEMS_15_NPC       = 1214;
const unsigned int __OBJGROUP_NATURE_ITEMS_16_NPC       = 1215;
const unsigned int __OBJGROUP_NATURE_ITEMS_17_NPC       = 1216;
const unsigned int __OBJGROUP_NATURE_ITEMS_18_NPC       = 1217;
const unsigned int __OBJGROUP_NATURE_ITEMS_19_NPC       = 1218;
const unsigned int __OBJGROUP_NATURE_ITEMS_20_NPC       = 1219;
const unsigned int __OBJGROUP_NATURE_ITEMS_21_NPC       = 1220;
const unsigned int __OBJGROUP_NATURE_ITEMS_22_NPC       = 1221;
const unsigned int __OBJGROUP_NATURE_ITEMS_23_NPC       = 1222;
const unsigned int __OBJGROUP_NATURE_ITEMS_24_NPC       = 1223;
const unsigned int __OBJGROUP_NATURE_ITEMS_25_NPC       = 1224;
const unsigned int __OBJGROUP_NATURE_ITEMS_26_NPC       = 1225;
const unsigned int __OBJGROUP_NATURE_ITEMS_27_NPC       = 1226;
const unsigned int __OBJGROUP_NATURE_ITEMS_28_NPC       = 1227;
const unsigned int __OBJGROUP_NATURE_ITEMS_29_NPC       = 1228;
const unsigned int __OBJGROUP_NATURE_ITEMS_30_NPC       = 1229;
const unsigned int __OBJGROUP_NATURE_ITEMS_31_NPC       = 1230;
const unsigned int __OBJGROUP_NATURE_ITEMS_32_NPC       = 1231;
const unsigned int __OBJGROUP_NATURE_ITEMS_33_NPC       = 1232;
const unsigned int __OBJGROUP_NATURE_ITEMS_34_NPC       = 1233;
const unsigned int __OBJGROUP_NATURE_ITEMS_35_NPC       = 1234;
const unsigned int __OBJGROUP_NATURE_ITEMS_36_NPC       = 1235;
const unsigned int __OBJGROUP_NATURE_ITEMS_37_NPC       = 1236;
const unsigned int __OBJGROUP_NATURE_ITEMS_38_NPC       = 1237;
const unsigned int __OBJGROUP_NATURE_ITEMS_39_NPC       = 1238;
const unsigned int __OBJGROUP_NATURE_ITEMS_40_NPC       = 1239;
const unsigned int __OBJGROUP_NATURE_ITEMS_41_NPC       = 1240;
const unsigned int __OBJGROUP_NATURE_ITEMS_42_NPC       = 1241;
const unsigned int __OBJGROUP_NATURE_ITEMS_43_NPC       = 1242;
const unsigned int __OBJGROUP_NATURE_ITEMS_44_NPC       = 1243;
const unsigned int __OBJGROUP_NATURE_ITEMS_45_NPC       = 1244;
const unsigned int __OBJGROUP_NATURE_ITEMS_46_NPC       = 1245;
const unsigned int __OBJGROUP_NATURE_ITEMS_47_NPC       = 1246;
const unsigned int __OBJGROUP_NATURE_ITEMS_48_NPC       = 1247;
const unsigned int __OBJGROUP_NATURE_ITEMS_49_NPC       = 1248;
const unsigned int __OBJGROUP_NATURE_ITEMS_50_NPC       = 1249;
const unsigned int __OBJGROUP_NATURE_ITEMS_51_NPC       = 1250;
const unsigned int __OBJGROUP_NATURE_ITEMS_52_NPC       = 1251;
const unsigned int __OBJGROUP_NATURE_ITEMS_53_NPC       = 1252;
const unsigned int __OBJGROUP_NATURE_ITEMS_54_NPC       = 1253;
const unsigned int __OBJGROUP_NATURE_ITEMS_55_NPC       = 1254;
const unsigned int __OBJGROUP_NATURE_ITEMS_56_NPC       = 1255;
const unsigned int __OBJGROUP_NATURE_ITEMS_57_NPC       = 1256;
const unsigned int __OBJGROUP_NATURE_ITEMS_58_NPC       = 1257;
const unsigned int __OBJGROUP_NATURE_ITEMS_59_NPC       = 1258;
const unsigned int __OBJGROUP_NATURE_ITEMS_60_NPC       = 1259;
const unsigned int __OBJGROUP_NATURE_ITEMS_61_NPC       = 1260;
const unsigned int __OBJGROUP_NATURE_ITEMS_62_NPC       = 1261;
const unsigned int __OBJGROUP_NATURE_ITEMS_63_NPC       = 1262;
const unsigned int __OBJGROUP_NATURE_ITEMS_64_NPC       = 1263;
const unsigned int __OBJGROUP_NATURE_ITEMS_65_NPC       = 1264;
const unsigned int __OBJGROUP_NATURE_ITEMS_66_NPC       = 1265;
const unsigned int __OBJGROUP_NATURE_ITEMS_67_NPC       = 1266;
const unsigned int __OBJGROUP_NATURE_ITEMS_68_NPC       = 1267;
const unsigned int __OBJGROUP_NATURE_ITEMS_69_NPC       = 1268;
const unsigned int __OBJGROUP_NATURE_ITEMS_70_NPC       = 1269;
const unsigned int __OBJGROUP_NATURE_ITEMS_71_NPC       = 1270;
const unsigned int __OBJGROUP_NATURE_ITEMS_72_NPC       = 1271;
const unsigned int __OBJGROUP_NATURE_ITEMS_73_NPC       = 1272;
const unsigned int __OBJGROUP_NATURE_ITEMS_74_NPC       = 1273;
const unsigned int __OBJGROUP_NATURE_ITEMS_75_NPC       = 1274;
const unsigned int __OBJGROUP_NATURE_ITEMS_76_NPC       = 1275;
const unsigned int __OBJGROUP_NATURE_ITEMS_77_NPC       = 1276;
const unsigned int __OBJGROUP_NATURE_ITEMS_78_NPC       = 1277;
const unsigned int __OBJGROUP_NATURE_ITEMS_79_NPC       = 1278;
const unsigned int __OBJGROUP_NATURE_ITEMS_80_NPC       = 1279;
const unsigned int __OBJGROUP_NATURE_ITEMS_81_NPC       = 1280;
const unsigned int __OBJGROUP_NATURE_ITEMS_82_NPC       = 1281;
const unsigned int __OBJGROUP_NATURE_ITEMS_83_NPC       = 1282;
const unsigned int __OBJGROUP_NATURE_ITEMS_84_NPC       = 1283;
const unsigned int __OBJGROUP_NATURE_ITEMS_85_NPC       = 1284;
const unsigned int __OBJGROUP_NATURE_ITEMS_86_NPC       = 1285;
const unsigned int __OBJGROUP_NATURE_ITEMS_87_NPC       = 1286;
const unsigned int __OBJGROUP_NATURE_ITEMS_88_NPC       = 1287;
const unsigned int __OBJGROUP_NATURE_ITEMS_89_NPC       = 1288;
const unsigned int __OBJGROUP_NATURE_ITEMS_90_NPC       = 1289;

const unsigned int __OBJGROUP_SNOW_BONHOMME01_NPC       = 1290;
const unsigned int __OBJGROUP_SNOW_BONHOMME01INV_NPC    = 1291;
const unsigned int __OBJGROUP_SNOW_BONHOMME02_NPC       = 1292;
const unsigned int __OBJGROUP_SNOW_BONHOMME02INV_NPC    = 1293;
const unsigned int __OBJGROUP_SNOW_BONHOMME03_NPC       = 1294;
const unsigned int __OBJGROUP_SNOW_BONHOMME03INV_NPC    = 1295;
const unsigned int __OBJGROUP_SNOW_TAS01_NPC            = 1296;
const unsigned int __OBJGROUP_SNOW_TAS02_NPC            = 1297;
const unsigned int __OBJGROUP_SNOW_TAS03_NPC            = 1298;

const unsigned int __OBJGROUP_NATURE_ITEMS_01_CON       = 1300;
const unsigned int __OBJGROUP_NATURE_ITEMS_02_CON       = 1301;
const unsigned int __OBJGROUP_NATURE_ITEMS_03_CON       = 1302;
const unsigned int __OBJGROUP_NATURE_ITEMS_04_CON       = 1303;
const unsigned int __OBJGROUP_NATURE_ITEMS_05_CON       = 1304;
const unsigned int __OBJGROUP_NATURE_ITEMS_06_CON       = 1305;
const unsigned int __OBJGROUP_NATURE_ITEMS_07_CON       = 1306;
const unsigned int __OBJGROUP_NATURE_ITEMS_08_CON       = 1307;
const unsigned int __OBJGROUP_NATURE_ITEMS_09_CON       = 1308;
const unsigned int __OBJGROUP_NATURE_ITEMS_10_CON       = 1309;
const unsigned int __OBJGROUP_NATURE_ITEMS_11_CON       = 1310;
const unsigned int __OBJGROUP_NATURE_ITEMS_12_CON       = 1311;
const unsigned int __OBJGROUP_NATURE_ITEMS_13_CON       = 1312;
const unsigned int __OBJGROUP_NATURE_ITEMS_14_CON       = 1313;
const unsigned int __OBJGROUP_NATURE_ITEMS_15_CON       = 1314;
const unsigned int __OBJGROUP_NATURE_ITEMS_16_CON       = 1315;
const unsigned int __OBJGROUP_NATURE_ITEMS_17_CON       = 1316;
const unsigned int __OBJGROUP_NATURE_ITEMS_18_CON       = 1317;
const unsigned int __OBJGROUP_NATURE_ITEMS_19_CON       = 1318;
const unsigned int __OBJGROUP_NATURE_ITEMS_20_CON       = 1319;
const unsigned int __OBJGROUP_NATURE_ITEMS_21_CON       = 1320;
const unsigned int __OBJGROUP_NATURE_ITEMS_22_CON       = 1321;
const unsigned int __OBJGROUP_NATURE_ITEMS_23_CON       = 1322;
const unsigned int __OBJGROUP_NATURE_ITEMS_24_CON       = 1323;
const unsigned int __OBJGROUP_NATURE_ITEMS_25_CON       = 1324;
const unsigned int __OBJGROUP_NATURE_ITEMS_26_CON       = 1325;
const unsigned int __OBJGROUP_NATURE_ITEMS_27_CON       = 1326;
const unsigned int __OBJGROUP_NATURE_ITEMS_28_CON       = 1327;
const unsigned int __OBJGROUP_NATURE_ITEMS_29_CON       = 1328;
const unsigned int __OBJGROUP_NATURE_ITEMS_30_CON       = 1329;
const unsigned int __OBJGROUP_NATURE_ITEMS_31_CON       = 1330;
const unsigned int __OBJGROUP_NATURE_ITEMS_32_CON       = 1331;
const unsigned int __OBJGROUP_NATURE_ITEMS_33_CON       = 1332;
const unsigned int __OBJGROUP_NATURE_ITEMS_34_CON       = 1333;
const unsigned int __OBJGROUP_NATURE_ITEMS_35_CON       = 1334;
const unsigned int __OBJGROUP_NATURE_ITEMS_36_CON       = 1335;
const unsigned int __OBJGROUP_NATURE_ITEMS_37_CON       = 1336;
const unsigned int __OBJGROUP_NATURE_ITEMS_38_CON       = 1337;
const unsigned int __OBJGROUP_NATURE_ITEMS_39_CON       = 1338;
const unsigned int __OBJGROUP_NATURE_ITEMS_40_CON       = 1339;
const unsigned int __OBJGROUP_NATURE_ITEMS_41_CON       = 1340;
const unsigned int __OBJGROUP_NATURE_ITEMS_42_CON       = 1341;
const unsigned int __OBJGROUP_NATURE_ITEMS_43_CON       = 1342;
const unsigned int __OBJGROUP_NATURE_ITEMS_44_CON       = 1343;
const unsigned int __OBJGROUP_NATURE_ITEMS_45_CON       = 1344;
const unsigned int __OBJGROUP_NATURE_ITEMS_46_CON       = 1345;
const unsigned int __OBJGROUP_NATURE_ITEMS_47_CON       = 1346;
const unsigned int __OBJGROUP_NATURE_ITEMS_48_CON       = 1347;
const unsigned int __OBJGROUP_NATURE_ITEMS_49_CON       = 1348;
const unsigned int __OBJGROUP_NATURE_ITEMS_50_CON       = 1349;
const unsigned int __OBJGROUP_NATURE_ITEMS_51_CON       = 1350;
const unsigned int __OBJGROUP_NATURE_ITEMS_52_CON       = 1351;
const unsigned int __OBJGROUP_NATURE_ITEMS_53_CON       = 1352;
const unsigned int __OBJGROUP_NATURE_ITEMS_54_CON       = 1353;
const unsigned int __OBJGROUP_NATURE_ITEMS_55_CON       = 1354;
const unsigned int __OBJGROUP_NATURE_ITEMS_56_CON       = 1355;
const unsigned int __OBJGROUP_NATURE_ITEMS_57_CON       = 1356;
const unsigned int __OBJGROUP_NATURE_ITEMS_58_CON       = 1357;
const unsigned int __OBJGROUP_NATURE_ITEMS_59_CON       = 1358;
const unsigned int __OBJGROUP_NATURE_ITEMS_60_CON       = 1359;
const unsigned int __OBJGROUP_NATURE_ITEMS_61_CON       = 1360;
const unsigned int __OBJGROUP_NATURE_ITEMS_62_CON       = 1361;
const unsigned int __OBJGROUP_NATURE_ITEMS_63_CON       = 1362;
const unsigned int __OBJGROUP_NATURE_ITEMS_64_CON       = 1363;
const unsigned int __OBJGROUP_NATURE_ITEMS_65_CON       = 1364;
const unsigned int __OBJGROUP_NATURE_ITEMS_66_CON       = 1365;
const unsigned int __OBJGROUP_NATURE_ITEMS_67_CON       = 1366;
const unsigned int __OBJGROUP_NATURE_ITEMS_68_CON       = 1367;
const unsigned int __OBJGROUP_NATURE_ITEMS_69_CON       = 1368;
const unsigned int __OBJGROUP_NATURE_ITEMS_70_CON       = 1369;
const unsigned int __OBJGROUP_NATURE_ITEMS_71_CON       = 1370;
const unsigned int __OBJGROUP_NATURE_ITEMS_72_CON       = 1371;
const unsigned int __OBJGROUP_NATURE_ITEMS_73_CON       = 1372;
const unsigned int __OBJGROUP_NATURE_ITEMS_74_CON       = 1373;
const unsigned int __OBJGROUP_NATURE_ITEMS_75_CON       = 1374;
const unsigned int __OBJGROUP_NATURE_ITEMS_76_CON       = 1375;
const unsigned int __OBJGROUP_NATURE_ITEMS_77_CON       = 1376;
const unsigned int __OBJGROUP_NATURE_ITEMS_78_CON       = 1377;
const unsigned int __OBJGROUP_NATURE_ITEMS_79_CON       = 1378;
const unsigned int __OBJGROUP_NATURE_ITEMS_80_CON       = 1379;
const unsigned int __OBJGROUP_NATURE_ITEMS_81_CON       = 1380;
const unsigned int __OBJGROUP_NATURE_ITEMS_82_CON       = 1381;
const unsigned int __OBJGROUP_NATURE_ITEMS_83_CON       = 1382;
const unsigned int __OBJGROUP_NATURE_ITEMS_84_CON       = 1383;
const unsigned int __OBJGROUP_NATURE_ITEMS_85_CON       = 1384;
const unsigned int __OBJGROUP_NATURE_ITEMS_86_CON       = 1385;
const unsigned int __OBJGROUP_NATURE_ITEMS_87_CON       = 1386;
const unsigned int __OBJGROUP_NATURE_ITEMS_88_CON       = 1387;
const unsigned int __OBJGROUP_NATURE_ITEMS_89_CON       = 1388;
const unsigned int __OBJGROUP_NATURE_ITEMS_90_CON       = 1389;

const unsigned int __OBJGROUP_WHIRLPOOL_BROWN           = 1390;
const unsigned int __OBJGROUP_WHIRLPOOL_GRAY            = 1410;
const unsigned int __OBJGROUP_WHIRLPOOL_BLACK           = 1430;

const unsigned int __OBJGROUP_SNOW_BONHOMME01_CON       = 1589;
const unsigned int __OBJGROUP_SNOW_BONHOMME01INV_CON    = 1590;
const unsigned int __OBJGROUP_SNOW_BONHOMME02_CON       = 1591;
const unsigned int __OBJGROUP_SNOW_BONHOMME02INV_CON    = 1592;
const unsigned int __OBJGROUP_SNOW_BONHOMME03_CON       = 1593;
const unsigned int __OBJGROUP_SNOW_BONHOMME03INV_CON    = 1594;
const unsigned int __OBJGROUP_SNOW_TAS01_CON            = 1595;
const unsigned int __OBJGROUP_SNOW_TAS02_CON            = 1596;
const unsigned int __OBJGROUP_SNOW_TAS03_CON            = 1597;

const unsigned int __OBJGROUP_STATUT_ACADEMIE_NPC       = 1598;
const unsigned int __OBJGROUP_STATUT_ACADEMIE_NPC_I     = 1599;


const unsigned int __OBJGROUP_NM_DEATH_AXE_2            = 1600;
const unsigned int __OBJGROUP_NM_DEATH_AXE_3            = 1601;
const unsigned int __OBJGROUP_NM_DEATH_AXE_4            = 1602;
const unsigned int __OBJGROUP_NM_DEATH_AXE_5            = 1603;
const unsigned int __OBJGROUP_FIRESWORD01_2             = 1604;
const unsigned int __OBJGROUP_FIRESWORD01_3             = 1605;
const unsigned int __OBJGROUP_FIRESWORD01_4             = 1606;
const unsigned int __OBJGROUP_FIRESWORD01_5             = 1607;
const unsigned int __OBJGROUP_FIRESWORD01DUAL_2         = 1608;
const unsigned int __OBJGROUP_FIRESWORD01DUAL_3         = 1609;
const unsigned int __OBJGROUP_FIRESWORD01DUAL_4         = 1610;
const unsigned int __OBJGROUP_FIRESWORD01DUAL_5         = 1611;

const unsigned int __OBJGROUP_SNOW_BONHOMME01_			= 1612;
const unsigned int __OBJGROUP_SNOW_BONHOMME01INV_		= 1613;
const unsigned int __OBJGROUP_SNOW_BONHOMME02_			= 1614;
const unsigned int __OBJGROUP_SNOW_BONHOMME02INV_		= 1615;
const unsigned int __OBJGROUP_SNOW_BONHOMME03_			= 1616;
const unsigned int __OBJGROUP_SNOW_BONHOMME03INV_		= 1617;
const unsigned int __OBJGROUP_SNOW_TAS01_				= 1618;
const unsigned int __OBJGROUP_SNOW_TAS02_				= 1619;
const unsigned int __OBJGROUP_SNOW_TAS03_				= 1620;





// New added by Dialsoft - END

const unsigned int __OBJGROUP_LASTGROUP                 = 2000; //Dois ajouter 900 ptete... a valider...


const unsigned int __OBJANIM_FONTAIN_02_CNT           = 21;
const unsigned int __OBJANIM_FONTAIN_02               = 2000;

const unsigned int __OBJLIGHT_LANTERNE1               = 2021;
const unsigned int __OBJLIGHT_CHANDELIER              = 2022;
const unsigned int __OBJLIGHT_POUTRE                  = 2023;
const unsigned int __OBJLIGHT_CHANDELLE2              = 2024;

const unsigned int __OBJANIM_MOULIND_CNT              = 15;
const unsigned int __OBJANIM_MOULIND                  = 2025;

const unsigned int __OBJANIM_MOULING_CNT              = 15;
const unsigned int __OBJANIM_MOULING                  = 2040;

const unsigned int __OBJANIM_SAPIN_CNT                = 32;
const unsigned int __OBJANIM_SAPIN_NOEL               = 2055;

const unsigned int __OBJANIM_NMS_FIRECAMP_CNT         = 22;
const unsigned int __OBJANIM_NMS_FIRECAMP             = 2087;

const unsigned int __OBJANIM_NMS_FLAG_CNT             = 10;
const unsigned int __OBJANIM_NMS_FLAGN                = 2109;
const unsigned int __OBJANIM_NMS_FLAGB                = 2119;
const unsigned int __OBJANIM_NMS_FLAGR                = 2129;

const unsigned int __OBJANIM_NMS_TANIMGRASS01_CNT     = 17;
const unsigned int __OBJANIM_NMS_TANIMGRASS01         = 2139;
const unsigned int __OBJANIM_NMS_TANIMGRASS02         = 2156;
const unsigned int __OBJANIM_NMS_TANIMGRASS03         = 2173;

const unsigned int __OBJLIGHT_CERBERUS_POD_01         = 2190;
const unsigned int __OBJLIGHT_CERBERUS_PODA_01        = 2191;

const unsigned int __OBJANIM_CERBERUS_POD_01_CNT      = 33;
const unsigned int __OBJANIM_CERBERUS_POD_01          = 2192;

const unsigned int __OBJLIGHT_WOOD_LANTERNE01         = 2225;
const unsigned int __OBJLIGHT_WOOD_LANTERNE01F        = 2226;

const unsigned int __OBJLIGHT_WOOD_LANTERNE02         = 2227;
const unsigned int __OBJLIGHT_WOOD_LANTERNE02F        = 2228;

const unsigned int __OBJLIGHT_WOOD_LANTERNEIRON01     = 2229;
const unsigned int __OBJLIGHT_WOOD_LANTERNEIRON02     = 2230;
const unsigned int __OBJLIGHT_WOOD_LANTERNEIRON03     = 2231;

const unsigned int __OBJANIM_FIRE_BOWL_CNT            = 16; //*2 pour coontenir l<alpha
const unsigned int __OBJANIM_FIRE_BOWL                = 2232;
const unsigned int __OBJANIM_FONTAINBLOOD_02_CNT      = 21;
const unsigned int __OBJANIM_FONTAINBLOOD_02          = 2248;

const unsigned int __OBJANIM_FIREPIT_A00_CNT          = 8;
const unsigned int __OBJANIM_FIREPIT_A00              = 2269;
const unsigned int __OBJANIM_FIREPIT_A00_INV_CNT      = 8;
const unsigned int __OBJANIM_FIREPIT_A00_INV          = 2277;
const unsigned int __OBJANIM_FIREPIT_A01_CNT          = 8;
const unsigned int __OBJANIM_FIREPIT_A01              = 2285;
const unsigned int __OBJANIM_FIREPIT_A01_INV_CNT      = 8;
const unsigned int __OBJANIM_FIREPIT_A01_INV          = 2293;
const unsigned int __OBJANIM_XaradonThrone_CNT = 8;
const unsigned int __OBJANIM_XaradonThrone = 2304;


//const unsigned int __OBJLIGHT_LAST                    = 2264;//tj le dernier ID
const unsigned int __OBJLIGHT_LAST                    = 3000;//tj le dernier ID


const unsigned int __OBJANIM_LASTGROUP                = (__OBJLIGHT_LAST-__OBJGROUP_LASTGROUP)+1;




static int const GET = 5; 
static int const USE = 4;	  
static int const TALK = 3;
static int const ATTACK = 2;
static int const NONE = 0;
static int const USE_ONSITE = 6;

static char DefaultMouseCursor[__OBJGROUP_LASTGROUP+__OBJANIM_LASTGROUP];

#endif