// ************************************************************************
// ***                                                                  ***
//      File Name: IDirectXSprite.Cpp
//      Project:   The Fourth Coming
//      Creation:  24 April, 1997
//      Author:    Benoit Thomas (TH)
// ***                                                                  ***
// ************************************************************************
// ***                                                                  ***
//      Change History
//
//         Date            Ver.	  Author	     Purpose
//         ----            ----    ------      -------
//         04-24-1997      1.0     TH          Initial development
//
//      Description
//         Provide fonction to load a Sprite into Image.
// ***                                                                  ***
//	************************************************************************
// *** Copyright (c) 1997-1998 Vircom. All rights reserved.             ***
#ifndef __DIRECTXSPRITE_H
#define __DIRECTXSPRITE_H     

#endif
